NS = actuino
VERSION ?= 1.0.1
REPO = unicorn-server-linux64

build:
	docker build -t $(NS)/$(REPO) -f Dockerfile.Linux64 .
	docker tag $(NS)/$(REPO) $(NS)/$(REPO):$(VERSION)
	#docker build -t $(NS)/$(REPO):$(VERSION) -f Dockerfile.Linux64 .
push:
	docker push $(NS)/$(REPO):$(VERSION)
	docker push $(NS)/$(REPO)

default: build